---
- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: '{{ home }}/.bashrc'
  register: bashrc_path

- name: Backup .bashrc
  ansible.builtin.shell:   
    cmd: mv '{{ home }}/.bashrc' '{{ home }}/.bashrc_old'
  when: bashrc_path.stat.exists == True 

- name: Download .bashrc
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jmrweb/files/main/configs/.bashrc
    dest: '{{ home }}'
    mode: '0644'

- name: Download .welcome
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jmrweb/files/main/configs/.welcome
    dest: '{{ home }}'
    mode: '0644'

- name: Check if .vimrc exists
  ansible.builtin.stat:
    path: '{{ home }}/.vimrc'
  register: vimrc_path

- name: Backup .vimrc
  ansible.builtin.shell:   
    cmd: mv '{{ home }}/.vimrc' '{{ home }}/.vimrc_old'
  when: vimrc_path.stat.exists == True 

- name: Download Matthew Hedley .vimrc
  ansible.builtin.get_url:
    url: https://xn0.org/.vimrc
    dest: '{{ home }}'
    mode: '0644'

- name: Check if .tmux.conf exists
  ansible.builtin.stat:
    path: '{{ home }}/.tmux.conf'
  register: tmuxconf_path

- name: Backup .tmux.conf
  ansible.builtin.shell:   
    cmd: mv '{{ home }}/.tmux.conf' '{{ home }}/.tmux.conf_old'
  when: tmuxconf_path.stat.exists == True 

- name: Download Matthew Hedley .tmux.conf
  ansible.builtin.get_url:
    url: https://xn0.org/.tmux.conf
    dest: '{{ home }}'
    mode: '0644'

- name: Create vim colors directoy
  ansible.builtin.file:
    path: '{{ home }}/.vim/colors'
    state: directory
    mode: '0755'
    owner: '{{ user }}'
    group: '{{ user }}'

- name: Download Matthew Hedley vim color file
  ansible.builtin.get_url:
    url: http://xn0.org/mmh.vim
    dest: '{{ home }}/.vim/colors'
    mode: '0644'

- name: Create ~/.config/joplin-desktop/ if it does not exist
  ansible.builtin.file:
    path: "{{ home }}/.config/joplin-desktop"
    state: directory
    mode: '0755'
    
- name: Download Joplin userstyle css config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jmrweb/files/main/joplin/userstyle.css
    dest: '{{ home }}/.config/joplin-desktop/'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
    
- name: Download Joplin userchrome css config
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jmrweb/files/main/joplin/userchrome.css
    dest: '{{ home }}/.config/joplin-desktop/'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'
