---
#- name: Get distribution release
#  ansible.builtin.debug:
#    msg:
#    - "Distro: {{ ansible_distribution }}"
#    - "Release: {{ ansible_distribution_release }}"

- name: Add VirtualBox signing key
  ansible.builtin.apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    
- name: Add VirtualBox repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    filename: virtualbox
    state: present



