---
#- name: Download Discord
#  ansible.builtin.get_url:
#    url: https://discord.com/api/download?platform=linux&format=deb
#    dest: /tmp/discord.deb
#    mode: '0755'

- name: Install Discord from internet
  ansible.builtin.apt:
    deb: https://discord.com/api/download?platform=linux&format=deb
