---
  - name: Pop OS setup playbook
    hosts: localhost
    connection: local
    become: true

    vars_prompt:
    - name: "cheat_ver"
      prompt: "Which version of cheat do you want to install?"
      default: "4.4.0"
      private: no
   
    vars:
      user: "{{ lookup('ansible.builtin.env','USER') }}"
      home: "{{ lookup('ansible.builtin.env','HOME') }}"

    roles:
      - add_repos
      - update
      - install_packages_popos
      - install_cheat
      - install_joplin
      - install_configs

    pre_tasks:

    
    post_tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

