---
- name: Check if cheat installed
  ansible.builtin.stat:
    path: /usr/local/bin/cheat
  register: cheat_installed

- name: Download cheat
  ansible.builtin.get_url:
    url: https://github.com/cheat/cheat/releases/download/{{ cheat_ver }}/cheat-linux-amd64.gz
    dest: /tmp
    mode: '0755'
  when: cheat_installed.stat.exists == False

- name: Unarchive and install cheat
  ansible.builtin.shell:
    cmd: gunzip /tmp/cheat-linux-amd64.gz && mv /tmp/cheat-linux-amd64 /usr/local/bin/cheat && chmod 755 /usr/local/bin/cheat
  when: cheat_installed.stat.exists == False

